# configuration
language: c
compiler: gcc

addons:
  apt:
    packages:
      - check
      - cmake

# go to the build directory
before_script:
  - mkdir Build
  - cd Build

# build and test
script:
  - cmake ..
  - cmake --build . --target all
  - ctest
